### ISSUE TITLE
Click to Shout not functional.

### ISSUE THREAD

**Issue by ghost** [KangasZ/EurekaHelper#3]
Click to Shout function is not working. Custom message shows up in chat window but clicking the orange text does nothing.

Click to Copy is working fine.

**Comment by KangasZ** [comment]
Appreciate the bug report, I'll take a look at this soon. Likely some offsets changed that I didn't catch in the latest update.

**Comment by ghost** [comment]
Appreciate all you do. This plugin has helped me run countless people through Eureka, even carried us to doing an FC wide BA, so any way I can pay back I will.

**Comment by KangasZ** [comment]
A fix has been pushed to the official Dalamud repo, should be working now.
